### ISSUE TITLE
Fails with Mardown input file

### ISSUE THREAD

**Issue by davidbrochart** [agronholm/release-notes#43]
Although I can see that the format is set to `"gfm"` if the input file extension is `.md`, `pandoc` is still called with:
```bash
pandoc -t json -o /tmp/tmptsv4fxvi/output.js -f md /tmp/tmptsv4fxvi/input
```
Which fails, see [here](https://github.com/jupyter-server/pycrdt/actions/runs/11324545694/job/31489891407). Maybe the Docker image is not updated with version `1.0.1`?

**Comment by agronholm** [comment]
Ahh...I think I need to force-push the `v1` tag.

**Comment by agronholm** [comment]
No, the v1 tag is up to date:
![kuva](https://github.com/user-attachments/assets/6c5ae3a0-31ef-4161-8b3b-68571aa9ba1e)

**Comment by agronholm** [comment]
Ah, so it's just the displayed version that looks off, due to this in the `Dockerfile`:
```
ENV SETUPTOOLS_SCM_PRETEND_VERSION_FOR_RELNOTES 1.0.0
```

**Comment by agronholm** [comment]
Could you try reproducing the issue locally?

**Comment by davidbrochart** [comment]
I couldn't, that's why I don't understand. But I guess explicitly setting `format: gfm` in my workflow would work.

**Comment by agronholm** [comment]
Can we figure out which git revision it's installing from?

**Comment by davidbrochart** [comment]
I'm using `agronholm/release-notes@v1`, I never know if I have to use `agronholm/release-notes@v1.0.1` explicitly?

**Comment by agronholm** [comment]
There is no `v1.0.1` tag though, use `1.0.1` instead.

**Comment by davidbrochart** [comment]
No, with `agronholm/release-notes@1.0.1` it didn't work : https://github.com/jupyter-server/pycrdt/actions/runs/11326472334/job/31495764615.

**Comment by agronholm** [comment]
Spotted this in your previous log:
```
Download action repository 'agronholm/release-notes@v1' (SHA:10d02927fda7989f3f54555214186339151c3ece)
```
This is the hash for v1.0.1.

**Comment by agronholm** [comment]
Can you verify which version of `pandoc` gets run locally for you where it actually works? Is the command exactly the same?

**Comment by davidbrochart** [comment]
I found the issue, opened #44.

**Comment by agronholm** [comment]
I've force-pushed the v1 tag now.

**Comment by davidbrochart** [comment]
Thanks, I confirm that it works now.
